### PR TITLE
Begin ArmorHud Implementation

### PR DESCRIPTION
**Pull request by Virusnest**
Implement Clientside armor hud that avoids the use of texturepacks for optimesed peformance and or accesability

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
will test soon

**Comment by DBTDerpbox** [comment]
am i doing something wrong? ive compiled it and joined a match and the clientside armorbar does not appear

**Comment by S-N00B-1** [comment]
It doesn’t get enabled, this also conflicts with custom world border

**Comment by kyrptonaught** [comment]
The pr purposely disables custom world border. Is there a reason for that?

**Comment by Virusnest** [comment]
Those were some upstream merge issues will fix soon

**Comment by Virusnest** [comment]
The armor hud is disabled so it doesn't conflict with existing hud untill a system for managing the HUD is found

**Comment by DBTDerpbox** [comment]
ill mention right now using `lem.base:arena` wont work as serverutils lies to the client and tells it the map name, so your client thinks you're in `lem.base:cove_largeplus` for example

**Comment by Virusnest** [comment]
Intresting because in my testing it returns lem.base:arena

**Comment by DBTDerpbox** [comment]
on the main server or toolbox?

-------- Original Message --------

**Comment by DBTDerpbox** [comment]
on the main server or toolbox?

**Comment by kyrptonaught** [comment]
We can make it just activate via packet from the server?

**Comment by Virusnest** [comment]
that should work and is not hard to implement

**Comment by DBTDerpbox** [comment]
if possible, a command on the server to tell the client when to display the armorbar and when to disable it would be helpful for both disabling it in the lobby and respecting user configs

**Comment by DBTDerpbox** [comment]
not sure if im doing something wrong, /armorHud @s true/false doesn't seem to do anything with both the serverutils and LCH PR

**Comment by DBTDerpbox** [comment]
issue is caused by [src/main/java/net/kyrptonaught/lemclienthelperhud/ArmorHud.java Line 28](https://github.com/Legacy-Edition-Minigames/LEMClientHelper/pull/3/files#diff-32d379d695498a5930ecb6f5abe95853269febda521c9a0c11efe80c86bc608eR28), setting `isGameActive` to false and `gameID` to null makes it work

are these two variables nessecary? all that really needs to exist for toggling armorbar is `/armorHud` enabling and disabling it, the datapack can handle the rest for when to actually turn it on and off

**Comment by DBTDerpbox** [comment]
ive also found an issue where the brightness of the armorbar isn't consistent, depending on if chat is open and what armor you're wearing it slightly changes brightness

**Comment by Virusnest** [comment]
yep let me take a look

**Comment by DBTDerpbox** [comment]
no chat
image

with chat
image

no chat with chestplate
image

chat with chestplate
image

**Comment by Virusnest** [comment]
Should be fixed now!

**Comment by DBTDerpbox** [comment]
both serverutils and LCH side seem to be working as intended

@kyrptonaught should i merge this PR and the one on serverutils?

**Comment by kyrptonaught** [comment]
Merging and testing

**Comment by DBTDerpbox** [comment]
will note, the main lem server and experimental don't have the updated datapacks for this yet

if you need me to host a server for you to join and test on i can

**Pull request merged**
