### PR TITLE
Begin Glide HUD Implementation

### PR DESCRIPTION
**Pull request by S-N00B-1**
Future-proofing for Glide

https://github.com/Legacy-Edition-Minigames/LEMClientHelper/assets/49575478/4dea39bc-804e-44c8-bc08-65083658c853

### CODE REVIEW

**Comment by S-N00B-1** [comment]
Speed text alignment fixed as of [2dee67b](https://github.com/Legacy-Edition-Minigames/LEMClientHelper/pull/7/commits/2dee67b178ea5e4108750bceeaa9048802af24b8)
It will no longer shift when passing 3 digits.

**Comment by S-N00B-1** [comment]
The implementation will need a lot of cleaning up.
https://github.com/Legacy-Edition-Minigames/LEMClientHelper/assets/49575478/4dea39bc-804e-44c8-bc08-65083658c853

**Comment by S-N00B-1** [comment]
[c8a89b9](https://github.com/Legacy-Edition-Minigames/LEMClientHelper/pull/7/commits/c8a89b9002a8f177dabbdc9786bfeca696209365) Should fix the issue with speed being calculated incorrectly. It was calculating based on rendering, and not based on ticks like the calculations assumed.

**Comment by DBTDerpbox** [comment]
did something happen?

**Comment by S-N00B-1** [comment]
I'm doing alot of cleanup.

**Pull request closed without merging**
